const { getJestProjects } = require('@nrwl/jest');

module.exports = {
  projects: [
    ...getJestProjects(),
    '<rootDir>/apps/hop-ui',
    '<rootDir>/libs/web/hop-shell/feature',
    '<rootDir>/libs/web/hop-shell/ui/layout',
    '<rootDir>/libs/web/hop-shell/ui/nav-bar',
    '<rootDir>/libs/web/hop-shell/ui/top-bar',
    '<rootDir>/libs/web/shared/ui/icons-provider',
    '<rootDir>/libs/web/settings/feature',
    '<rootDir>/libs/web/settings/data-access',
    '<rootDir>/libs/web/hop-home/feature',
    '<rootDir>/libs/web/shared/ui/zorro-provider',
    '<rootDir>/libs/web/auth/feature/shell',
    '<rootDir>/libs/web/auth/feature/login',
    '<rootDir>/libs/web/auth/ui/login-form',
    '<rootDir>/libs/web/auth/data-access',
    '<rootDir>/libs/web/auth/ui/layout',
    '<rootDir>/libs/web/shared/ui/layout',
    '<rootDir>/libs/web/hop/feature/shell/hop-shell',
    '<rootDir>/libs/web/hop/feature/hop-shell',
    '<rootDir>/libs/web/hop/feature/hop-home',
    '<rootDir>/libs/web/hop-shell/feature/hop-shell',
    '<rootDir>/libs/web/auth/utils',
    '<rootDir>/libs/web/core',
    '<rootDir>/libs/web/service-req/feature/shell',
    '<rootDir>/libs/web/service-req/feature/service-request',
    '<rootDir>/libs/web/service-req/ui/service-request-form',
    '<rootDir>/libs/web/service-req/data-access',
    '<rootDir>/libs/web/service-req/utils',
    '<rootDir>/libs/web/service-req/data-access/model',
    '<rootDir>/apps/whoa-apis',
    '<rootDir>/libs/api/passport/feature',
    '<rootDir>/libs/api/core/feature',
    '<rootDir>/libs/api/hoa-board/feature',
    '<rootDir>/libs/api/hoa-property/feature'
  ]
};
