version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - c:/dev/tools/postgres-data/:/data/postgres
    env_file:
    - .env.docker
    networks:
    - whoa-network
 
  pgadmin:
    container_name: pgadmin
    links:
    - postgres:postgres
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - c:/dev/tools/pgadmin-data:/root/.pgadmin
    env_file:
    - .env.docker
    networks:
    - whoa-network
    depends_on:
    - postgres

  keycloak:
    container_name: keycloak
    links:
    - postgres:postgres
    image: quay.io/keycloak/keycloak:latest
    ports:
    - "8090:8080"
    env_file:
    - .env.docker
    networks:
    - whoa-network
    depends_on:
    - postgres

networks:
  whoa-network:
    driver: bridge